apiVersion: apps/v1
kind: Deployment
metadata:
  name: apartment-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apartment-api
  template:
    metadata:
      labels:
        app: apartment-api
    spec:
      containers:
        - name: apartment-api-container
          image: apartment-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
